name: Release
# This workflow is triggered when a new tag is published
# `git tag v0.0.1`
# `git push --tags`
# If the tag already exists, use this commanf to delete it `git tag -d v0.0.1`

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    if: contains(github.ref, 'tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      v_num:  ${{ steps.version.outputs.number }}


    steps:
      - uses: actions/checkout@v4

      - name: Get version number
        id: version
        run: echo "number=${{ github.ref_name }}" >>$GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
         